"use server"

import { query } from "@/lib/db"
import { adminActionAuthorized } from "@/lib/admin-auth"
import { type UserProfile } from "@/lib/users"
import { resolveCurrentSession } from "@/lib/session-user"
import { logActivity } from "@/app/actions/log-activity"
import { isValidIsin, isValidCusip } from "@/lib/instrument-identifiers"
import { mapIsinServer } from "@/lib/openfigi-server"
import { resolveIsinEntity } from "@/lib/gleif-server"
import { lookupBankByBic, lookupBankByName } from "@/lib/iban-swift"
import { getCountryByCode } from "@/lib/countries"

// ---------------------------------------------------------------------------
// Marketplace bank-instrument catalogue (REAL data only).
//
// The old marketplace fabricated ISINs and Common Codes with a deterministic
// generator so they "looked authentic". That is gone. The catalogue is now
// populated EXCLUSIVELY by administrator uploads, and every instrument carries:
//
//   • an ISIN that passes structural + check-digit validation, AND
//   • a verification provenance from a REAL registry — Bloomberg (live via
//     OpenFIGI), Euroclear, or Clearstream. Bloomberg-sourced ISINs are
//     hard-verified live at publish time (must resolve to a real security);
//     Euroclear/Clearstream-sourced instruments must carry the real 9-digit
//     Common Code from the ICSD admission.
//
// Nothing is ever generated by code. A Common Code is NOT derivable from an
// ISIN (the ICSDs assign it independently), so the admin enters the real value
// and we only validate its format — we never invent one.
//
// Reads fail CLOSED: if the table is unavailable the marketplace shows nothing,
// never fabricated data.
// ---------------------------------------------------------------------------

export type VerifiedSource = "bloomberg" | "euroclear" | "clearstream"

/** The four trusted verification registries shown per instrument. */
export type VerificationRegistry = "bloomberg" | "euroclear" | "clearstream" | "swift"

/**
 * Per-registry verification provenance. Each value is the ISO timestamp the
 * instrument was confirmed against that registry, or null if not verified.
 * Bloomberg is set automatically when the ISIN resolves live via OpenFIGI;
 * Euroclear / Clearstream / SWIFT are admin-attested with the date recorded.
 */
export type Verifications = Record<VerificationRegistry, string | null>

export interface MarketplaceInstrument {
  id: string
  isin: string
  cusip: string | null
  commonCode: string | null
  bankName: string
  bankBic: string
  bankCountry: string
  type: string
  typeFull: string
  faceValue: number
  currency: string
  tenorMonths: number
  rating: string
  assignable: boolean
  monetizable: boolean
  available: boolean
  // Verification provenance
  verifiedSource: VerifiedSource
  verifiedFigi: string | null
  verifiedName: string | null
  verifiedAt: string | null
  // Per-registry verification status (Bloomberg/Euroclear/Clearstream/SWIFT)
  verifications: Verifications
  // Printout / tearsheet fields
  issueDate: string | null
  maturityDate: string | null
  issuerDetails: string | null
  beneficiaryTerms: string | null
  deliveryMethod: string | null
  governingLaw: string | null
  notes: string | null
  printoutUrl: string | null
  createdAt: string
}

export interface PublishInstrumentInput {
  isin: string
  cusip?: string | null
  commonCode?: string | null
  bankName: string
  bankBic?: string
  bankCountry?: string
  type: string
  typeFull: string
  faceValue: number
  currency: string
  tenorMonths: number
  rating?: string
  assignable?: boolean
  monetizable?: boolean
  verifiedSource: VerifiedSource
  // Admin attestations that the instrument was confirmed against each registry.
  attestEuroclear?: boolean
  attestClearstream?: boolean
  attestSwift?: boolean
  issueDate?: string | null
  maturityDate?: string | null
  issuerDetails?: string | null
  beneficiaryTerms?: string | null
  deliveryMethod?: string | null
  governingLaw?: string | null
  notes?: string | null
  printoutUrl?: string | null
}

/**
 * Fields an administrator may edit on an already-published instrument. The
 * verified identity (ISIN) and its verification provenance (source / Bloomberg
 * figi / registry attestations) are intentionally immutable — changing them
 * would invalidate the verification, so a mis-verified instrument must instead
 * be removed and re-published. Everything commercial / descriptive is editable.
 */
export interface UpdateInstrumentInput {
  id: string
  cusip?: string | null
  commonCode?: string | null
  bankName: string
  bankBic?: string
  bankCountry?: string
  type: string
  typeFull: string
  faceValue: number
  currency: string
  tenorMonths: number
  rating?: string
  assignable?: boolean
  monetizable?: boolean
  issueDate?: string | null
  maturityDate?: string | null
  issuerDetails?: string | null
  beneficiaryTerms?: string | null
  deliveryMethod?: string | null
  governingLaw?: string | null
  notes?: string | null
  printoutUrl?: string | null
}

export type MarketplaceResult =
  | { ok: true; instruments: MarketplaceInstrument[] }
  | { ok: false; error: string }

export type PublishResult =
  | { ok: true; instrument: MarketplaceInstrument; instruments: MarketplaceInstrument[] }
  | { ok: false; error: string }

async function getSessionUser(): Promise<UserProfile | undefined> {
  const session = await resolveCurrentSession()
  return session?.profile
}

async function requireAdmin(passcode: string): Promise<UserProfile> {
  const user = await getSessionUser()
  if (!user) throw new Error("Your session has expired. Please sign in again.")
  if (!(await adminActionAuthorized(passcode))) throw new Error("Administrator authorization failed.")
  return user
}

let ensured = false
async function ensureTable(): Promise<void> {
  if (ensured) return
  await query(
    `CREATE TABLE IF NOT EXISTS marketplace_instruments (
       id                text        PRIMARY KEY,
       isin              text        NOT NULL,
       common_code       text,
       bank_name         text        NOT NULL,
       bank_bic          text        NOT NULL DEFAULT '',
       bank_country      text        NOT NULL DEFAULT '',
       type              text        NOT NULL,
       type_full         text        NOT NULL,
       face_value        numeric     NOT NULL DEFAULT 0,
       currency          text        NOT NULL DEFAULT 'USD',
       tenor_months      integer     NOT NULL DEFAULT 12,
       rating            text        NOT NULL DEFAULT '',
       assignable        boolean     NOT NULL DEFAULT true,
       monetizable       boolean     NOT NULL DEFAULT true,
       available         boolean     NOT NULL DEFAULT true,
       verified_source   text        NOT NULL,
       verified_figi     text,
       verified_name     text,
       verified_at       timestamptz,
       issue_date        date,
       maturity_date     date,
       issuer_details    text,
       beneficiary_terms text,
       delivery_method   text,
       governing_law     text,
       notes             text,
       printout_url      text,
       created_by        text,
       created_at        timestamptz NOT NULL DEFAULT now(),
       updated_at        timestamptz NOT NULL DEFAULT now()
     )`,
  )
  // Backward-compatible additive columns (CUSIP + multi-registry attestations).
  await query(`ALTER TABLE marketplace_instruments ADD COLUMN IF NOT EXISTS cusip text`)
  await query(`ALTER TABLE marketplace_instruments ADD COLUMN IF NOT EXISTS attested_bloomberg timestamptz`)
  await query(`ALTER TABLE marketplace_instruments ADD COLUMN IF NOT EXISTS attested_euroclear timestamptz`)
  await query(`ALTER TABLE marketplace_instruments ADD COLUMN IF NOT EXISTS attested_clearstream timestamptz`)
  await query(`ALTER TABLE marketplace_instruments ADD COLUMN IF NOT EXISTS attested_swift timestamptz`)
  ensured = true
}

function toIso(v: unknown): string | null {
  if (!v) return null
  if (v instanceof Date) return v.toISOString()
  return String(v)
}

function toDateString(v: unknown): string | null {
  if (!v) return null
  if (v instanceof Date) return v.toISOString().slice(0, 10)
  const s = String(v)
  return s.length >= 10 ? s.slice(0, 10) : s
}

function rowToInstrument(row: Record<string, unknown>): MarketplaceInstrument {
  return {
    id: row.id as string,
    isin: row.isin as string,
    cusip: (row.cusip as string | null) ?? null,
    commonCode: (row.common_code as string | null) ?? null,
    bankName: row.bank_name as string,
    bankBic: (row.bank_bic as string) ?? "",
    bankCountry: (row.bank_country as string) ?? "",
    type: row.type as string,
    typeFull: row.type_full as string,
    faceValue: Number(row.face_value),
    currency: row.currency as string,
    tenorMonths: Number(row.tenor_months),
    rating: (row.rating as string) ?? "",
    assignable: row.assignable as boolean,
    monetizable: row.monetizable as boolean,
    available: row.available as boolean,
    verifiedSource: row.verified_source as VerifiedSource,
    verifiedFigi: (row.verified_figi as string | null) ?? null,
    verifiedName: (row.verified_name as string | null) ?? null,
    verifiedAt: (row.verified_at as Date)?.toISOString?.() ?? (row.verified_at as string | null) ?? null,
    verifications: {
      // Fall back to the legacy single-source columns for rows created before
      // per-registry attestation existed, so nothing is mis-reported.
      bloomberg:
        toIso(row.attested_bloomberg) ??
        (row.verified_source === "bloomberg" ? toIso(row.verified_at) : null),
      euroclear:
        toIso(row.attested_euroclear) ??
        (row.verified_source === "euroclear" ? toIso(row.verified_at) : null),
      clearstream:
        toIso(row.attested_clearstream) ??
        (row.verified_source === "clearstream" ? toIso(row.verified_at) : null),
      swift: toIso(row.attested_swift),
    },
    issueDate: toDateString(row.issue_date),
    maturityDate: toDateString(row.maturity_date),
    issuerDetails: (row.issuer_details as string | null) ?? null,
    beneficiaryTerms: (row.beneficiary_terms as string | null) ?? null,
    deliveryMethod: (row.delivery_method as string | null) ?? null,
    governingLaw: (row.governing_law as string | null) ?? null,
    notes: (row.notes as string | null) ?? null,
    printoutUrl: (row.printout_url as string | null) ?? null,
    createdAt: (row.created_at as Date)?.toISOString?.() ?? (row.created_at as string) ?? "",
  }
}

// ---------------------------------------------------------------------------
// Client-callable read (no passcode). Only AVAILABLE, published instruments.
// Fails CLOSED — returns [] on any error, never fabricated data.
// ---------------------------------------------------------------------------
export async function getPublishedInstruments(): Promise<MarketplaceInstrument[]> {
  try {
    await ensureTable()
    const { rows } = await query(
      `SELECT * FROM marketplace_instruments WHERE available = true ORDER BY created_at DESC`,
    )
    return rows.map(rowToInstrument)
  } catch (err) {
    console.log("[v0] getPublishedInstruments failed:", (err as Error).message)
    return []
  }
}

// ---------------------------------------------------------------------------
// Admin: full catalogue (published + unavailable), passcode verified.
// ---------------------------------------------------------------------------
export async function getAdminMarketplaceInstruments(passcode: string): Promise<MarketplaceResult> {
  try {
    await requireAdmin(passcode)
    await ensureTable()
    const { rows } = await query(`SELECT * FROM marketplace_instruments ORDER BY created_at DESC`)
    return { ok: true, instruments: rows.map(rowToInstrument) }
  } catch (err) {
    return { ok: false, error: (err as Error).message }
  }
}

/** Validate a Common Code: exactly 9 digits, or empty/null. */
function normalizeCommonCode(raw: string | null | undefined): { ok: true; value: string | null } | { ok: false } {
  const v = (raw ?? "").trim()
  if (!v) return { ok: true, value: null }
  if (!/^\d{9}$/.test(v)) return { ok: false }
  return { ok: true, value: v }
}

// ---------------------------------------------------------------------------
// Admin: auto-fill reference data for an ISIN from REAL sources only.
//
// Combines three authoritative sources and returns only what they actually
// yield — anything unknown stays blank for the admin to complete. Nothing here
// is generated or guessed:
//   • ISIN prefix  → issuer country (deterministic ISO 3166).
//   • OpenFIGI     → security / issuer name, instrument type (Bloomberg-listed).
//   • GLEIF        → legal entity name, registered address, SWIFT/BIC, country.
//   • Local BIC directory → street address / city enrichment for a known BIC.
// ---------------------------------------------------------------------------
export interface InstrumentEnrichment {
  bankName: string | null
  bankBic: string | null
  bankCountry: string | null
  issuerDetails: string | null
  securityName: string | null
  securityType: string | null
  bloombergListed: boolean
  /** Human-readable list of the sources that actually contributed data. */
  sources: string[]
}

/**
 * A lightweight reference to an instrument that already exists in the
 * catalogue, returned when a newly-entered identifier collides with one on the
 * platform. `field` records which identifier matched so the UI can be specific.
 */
export interface ExistingInstrumentRef {
  id: string
  isin: string
  bankName: string
  typeFull: string
  createdAt: string
  field: "isin" | "cusip" | "commonCode"
}

export type EnrichResult =
  | { ok: true; enrichment: InstrumentEnrichment; duplicate: ExistingInstrumentRef | null }
  | { ok: false; error: string }

/**
 * Find an already-published instrument that shares any unique identifier with
 * the supplied values (ISIN, CUSIP, or ICSD Common Code). Comparison is
 * case-insensitive and returns the first collision, prioritising the ISIN.
 * Returns null when the values are free — or if the table doesn't exist yet.
 */
async function findDuplicateInstrument(opts: {
  isin: string
  cusip?: string | null
  commonCode?: string | null
  /** Instrument id to ignore — used when editing so a row never collides with itself. */
  excludeId?: string | null
}): Promise<ExistingInstrumentRef | null> {
  const isin = (opts.isin || "").trim().toUpperCase()
  const cusip = (opts.cusip || "").trim().toUpperCase() || null
  const commonCode = (opts.commonCode || "").trim() || null
  const excludeId = (opts.excludeId || "").trim() || null
  if (!isin && !cusip && !commonCode) return null

  try {
    const { rows } = await query(
      `SELECT id, isin, cusip, common_code, bank_name, type_full, created_at
         FROM marketplace_instruments
        WHERE ($4::text IS NULL OR id <> $4)
          AND (
            upper(isin) = $1
            OR ($2::text IS NOT NULL AND upper(cusip) = $2)
            OR ($3::text IS NOT NULL AND common_code = $3)
          )
        ORDER BY (upper(isin) = $1) DESC, created_at ASC
        LIMIT 1`,
      [isin, cusip, commonCode, excludeId],
    )
    const row = rows[0]
    if (!row) return null
    const field: ExistingInstrumentRef["field"] =
      String(row.isin ?? "").toUpperCase() === isin
        ? "isin"
        : cusip && String(row.cusip ?? "").toUpperCase() === cusip
          ? "cusip"
          : "commonCode"
    return {
      id: row.id as string,
      isin: row.isin as string,
      bankName: (row.bank_name as string) ?? "",
      typeFull: (row.type_full as string) ?? "",
      createdAt: toIso(row.created_at) ?? "",
      field,
    }
  } catch (err) {
    // Table missing / transient read error → treat as no duplicate (publish
    // still has its own guard), never block enrichment on a read failure.
    console.log("[v0] findDuplicateInstrument failed:", (err as Error).message)
    return null
  }
}

export async function enrichInstrumentFromIsin(passcode: string, isin: string): Promise<EnrichResult> {
  try {
    await requireAdmin(passcode)
  } catch {
    return { ok: false, error: "Not authorized." }
  }

  const clean = (isin || "").trim().toUpperCase()
  if (!isValidIsin(clean)) {
    return { ok: false, error: "Enter a valid 12-character ISIN first." }
  }

  const sources: string[] = []
  const e: InstrumentEnrichment = {
    bankName: null,
    bankBic: null,
    bankCountry: null,
    issuerDetails: null,
    securityName: null,
    securityType: null,
    bloombergListed: false,
    sources,
  }

  // 1) Country from the ISIN prefix (deterministic, always real).
  const prefix = clean.slice(0, 2)
  const prefixCountry = getCountryByCode(prefix)
  if (prefixCountry) {
    e.bankCountry = prefixCountry.name
    sources.push("ISIN country prefix")
  }

  // 2) OpenFIGI (Bloomberg) + 3) GLEIF, in parallel — both real, both optional.
  const [figi, gleif] = await Promise.all([
    mapIsinServer(clean).catch(() => null),
    resolveIsinEntity(clean).catch(() => null),
  ])

  if (figi?.listed && figi.matches[0]) {
    e.bloombergListed = true
    const m = figi.matches[0]
    e.securityName = m.name ?? m.securityDescription ?? null
    e.securityType = m.securityType2 ?? m.securityType ?? null
    if (e.securityName || e.securityType) sources.push("Bloomberg / OpenFIGI")
  }

  if (gleif) {
    if (gleif.legalName) e.bankName = gleif.legalName
    if (gleif.bic) e.bankBic = gleif.bic
    if (gleif.address) e.issuerDetails = gleif.address
    // GLEIF's legal-address country is more precise than the ISIN prefix.
    if (gleif.countryCode) {
      const c = getCountryByCode(gleif.countryCode)
      if (c) e.bankCountry = c.name
    }
    if (gleif.legalName || gleif.bic || gleif.address) sources.push("GLEIF (LEI registry)")
  }

  // 4) If we have a BIC but GLEIF gave no street address, enrich from the local
  //    curated bank directory (also real, curated data).
  if (e.bankBic && !e.issuerDetails) {
    try {
      const info = await lookupBankByBic(e.bankBic)
      if (info) {
        if (!e.bankName && info.name) e.bankName = info.name
        const line = [info.address, info.city, info.postalCode, info.country]
          .filter((p) => p && String(p).trim())
          .join(", ")
        if (line) {
          e.issuerDetails = line
          sources.push("Bank directory")
        }
      }
    } catch {
      // non-fatal
    }
  }

  // 5) GLEIF frequently returns a legal name + address but NO BIC, and some
  //    ISINs don't resolve there at all. Cross-reference the resolved issuer /
  //    security name against the curated bank directory to fill any remaining
  //    SWIFT/BIC, registered address, bank name or country from real data.
  const nameForLookup = e.bankName || e.securityName
  if (nameForLookup && (!e.bankBic || !e.issuerDetails || !e.bankCountry || !e.bankName)) {
    try {
      const byName = await lookupBankByName(nameForLookup)
      if (byName) {
        if (!e.bankName && byName.name) e.bankName = byName.name
        if (!e.bankBic && byName.bic) e.bankBic = byName.bic
        if (!e.bankCountry && byName.country) e.bankCountry = byName.country
        if (!e.issuerDetails) {
          const line = [byName.address, byName.city, byName.postalCode, byName.country]
            .filter((p) => p && String(p).trim())
            .join(", ")
          if (line) e.issuerDetails = line
        }
        if (!sources.includes("Bank directory")) sources.push("Bank directory")
      }
    } catch {
      // non-fatal
    }
  }

  // Flag if this ISIN is already on the platform so the admin is warned before
  // publishing rather than being rejected only at the end.
  const duplicate = await findDuplicateInstrument({ isin: clean })

  return { ok: true, enrichment: e, duplicate }
}

// ---------------------------------------------------------------------------
// Admin: publish a new instrument. This is the integrity gate.
// ---------------------------------------------------------------------------
export async function publishInstrument(
  passcode: string,
  input: PublishInstrumentInput,
): Promise<PublishResult> {
  let admin: UserProfile
  try {
    admin = await requireAdmin(passcode)
  } catch (err) {
    return { ok: false, error: (err as Error).message }
  }

  const isin = (input.isin ?? "").trim().toUpperCase()
  if (!isValidIsin(isin)) {
    return { ok: false, error: "Invalid ISIN — it must be 12 characters with a correct check digit." }
  }
  if (!input.bankName?.trim()) return { ok: false, error: "Issuing bank name is required." }
  if (!input.type?.trim() || !input.typeFull?.trim()) {
    return { ok: false, error: "Instrument type is required." }
  }
  if (!Number.isFinite(input.faceValue) || input.faceValue <= 0) {
    return { ok: false, error: "Face value must be a positive number." }
  }
  const source = input.verifiedSource
  if (source !== "bloomberg" && source !== "euroclear" && source !== "clearstream") {
    return { ok: false, error: "Choose a verification source: Bloomberg, Euroclear, or Clearstream." }
  }

  const cc = normalizeCommonCode(input.commonCode)
  if (!cc.ok) {
    return { ok: false, error: "Common Code must be exactly 9 digits (Euroclear/Clearstream), or left blank." }
  }

  // CUSIP is optional, but when supplied it must be a real, check-digit-valid
  // 9-character CUSIP — never fabricated or auto-corrected.
  const cusipRaw = (input.cusip ?? "").trim().toUpperCase()
  const cusip = cusipRaw || null
  if (cusip && !isValidCusip(cusip)) {
    return { ok: false, error: "Invalid CUSIP — it must be 9 characters with a correct check digit, or left blank." }
  }

  // Euroclear/Clearstream provenance requires the real ICSD Common Code.
  if ((source === "euroclear" || source === "clearstream") && !cc.value) {
    return {
      ok: false,
      error: "A 9-digit Common Code is required to publish an Euroclear/Clearstream-verified instrument.",
    }
  }

  // Live registry verification against Bloomberg (OpenFIGI).
  // Only performed for Bloomberg-sourced instruments: bilateral bank instruments
  // published under Euroclear/Clearstream are never exchange-listed, so calling
  // OpenFIGI for them only adds latency (and, if the API stalls, a hang). Those
  // are gated by their real Common Code instead.
  let verifiedFigi: string | null = null
  let verifiedName: string | null = null
  let bloombergListed = false
  if (source === "bloomberg") {
    try {
      const mapping = await mapIsinServer(isin)
      if (mapping.listed && mapping.matches[0]) {
        bloombergListed = true
        verifiedFigi = mapping.matches[0].figi ?? null
        verifiedName = mapping.matches[0].name ?? mapping.matches[0].securityDescription ?? null
      }
      // Bloomberg provenance is a HARD gate: the ISIN must resolve live.
      if (!mapping.listed) {
        return {
          ok: false,
          error:
            "This ISIN does not resolve to a listed security on Bloomberg. Bilateral instruments (SBLC/BG/private MTNs) are not Bloomberg-listed — publish them as Euroclear or Clearstream with their Common Code instead.",
        }
      }
    } catch (err) {
      console.log("[v0] publishInstrument verification failed:", (err as Error).message)
      return { ok: false, error: "Bloomberg verification is temporarily unavailable. Please try again." }
    }
  }

  const id = `MKT-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`

  // Per-registry attestation timestamps. Bloomberg is set only when the ISIN
  // actually resolved live; the ICSDs/SWIFT are set from the admin attestation
  // (the primary source is always treated as attested).
  const nowTs = new Date()
  const attestedBloomberg = bloombergListed ? nowTs : null
  const attestedEuroclear = input.attestEuroclear || source === "euroclear" ? nowTs : null
  const attestedClearstream = input.attestClearstream || source === "clearstream" ? nowTs : null
  const attestedSwift = input.attestSwift ? nowTs : null

  try {
    await ensureTable()

    // Authoritative duplicate guard: never allow the same ISIN, CUSIP, or ICSD
    // Common Code to be published twice. This runs after the (cheaper) format
    // checks and, for Bloomberg, after live verification — but the collision is
    // decided here against what's actually in the catalogue.
    const dup = await findDuplicateInstrument({ isin, cusip, commonCode: cc.value })
    if (dup) {
      const fieldLabel =
        dup.field === "isin" ? `ISIN ${isin}` : dup.field === "cusip" ? `CUSIP ${cusip}` : `Common Code ${cc.value}`
      return {
        ok: false,
        error: `This ${fieldLabel} is already on the platform — published as ${dup.typeFull || "an instrument"} from ${dup.bankName || "an issuer"} (${dup.id}). Duplicate instruments are not allowed.`,
      }
    }

    await query(
      `INSERT INTO marketplace_instruments (
         id, isin, cusip, common_code, bank_name, bank_bic, bank_country, type, type_full,
         face_value, currency, tenor_months, rating, assignable, monetizable, available,
         verified_source, verified_figi, verified_name, verified_at,
         attested_bloomberg, attested_euroclear, attested_clearstream, attested_swift,
         issue_date, maturity_date, issuer_details, beneficiary_terms, delivery_method,
         governing_law, notes, printout_url, created_by, created_at, updated_at
       ) VALUES (
         $1, $2, $3, $4, $5, $6, $7, $8, $9,
         $10, $11, $12, $13, $14, $15, true,
         $16, $17, $18, now(),
         $19, $20, $21, $22,
         $23, $24, $25, $26, $27,
         $28, $29, $30, $31, now(), now()
       )`,
      [
        id,
        isin,
        cusip,
        cc.value,
        input.bankName.trim(),
        (input.bankBic ?? "").trim(),
        (input.bankCountry ?? "").trim(),
        input.type.trim(),
        input.typeFull.trim(),
        Math.round(input.faceValue),
        (input.currency ?? "USD").trim().toUpperCase(),
        Math.max(1, Math.round(input.tenorMonths || 12)),
        (input.rating ?? "").trim(),
        input.assignable ?? true,
        input.monetizable ?? true,
        source,
        verifiedFigi,
        verifiedName,
        attestedBloomberg,
        attestedEuroclear,
        attestedClearstream,
        attestedSwift,
        input.issueDate || null,
        input.maturityDate || null,
        (input.issuerDetails ?? "").trim() || null,
        (input.beneficiaryTerms ?? "").trim() || null,
        (input.deliveryMethod ?? "").trim() || null,
        (input.governingLaw ?? "").trim() || null,
        (input.notes ?? "").trim() || null,
        (input.printoutUrl ?? "").trim() || null,
        `${admin.fullName} (${admin.company})`,
      ],
    )

    const sourceLabel =
      source === "bloomberg" ? "Bloomberg (live-verified)" : source === "euroclear" ? "Euroclear" : "Clearstream"
    await logActivity({
      action: `Administrator published ${input.type} to the instrument marketplace`,
      category: "Bank Instruments",
      user: `${admin.fullName} (${admin.company})`,
      details: {
        summary: `Administrator published a ${input.typeFull} (${input.type}) from ${input.bankName} with ISIN ${isin}${cc.value ? ` and Common Code ${cc.value}` : ""}, verified via ${sourceLabel}${verifiedFigi ? ` (Bloomberg ID ${verifiedFigi})` : ""}.`,
        isin,
        commonCode: cc.value ?? "—",
        verifiedSource: sourceLabel,
        bloombergId: verifiedFigi ?? "—",
        instrumentType: `${input.type} — ${input.typeFull}`,
        issuingBank: input.bankName,
      },
    })

    const { rows } = await query(`SELECT * FROM marketplace_instruments ORDER BY created_at DESC`)
    const all = rows.map(rowToInstrument)
    const created = all.find((i) => i.id === id)!
    return { ok: true, instrument: created, instruments: all }
  } catch (err) {
    console.log("[v0] publishInstrument failed:", (err as Error).message)
    return { ok: false, error: "The instrument could not be published. Please try again." }
  }
}

// ---------------------------------------------------------------------------
// Admin: toggle availability (hide/show without deleting).
// ---------------------------------------------------------------------------
export async function setInstrumentAvailability(
  passcode: string,
  id: string,
  available: boolean,
): Promise<MarketplaceResult> {
  try {
    const admin = await requireAdmin(passcode)
    await ensureTable()
    await query(
      `UPDATE marketplace_instruments SET available = $2, updated_at = now() WHERE id = $1`,
      [id, available],
    )
    await logActivity({
      action: `Administrator ${available ? "listed" : "hid"} a marketplace instrument`,
      category: "Bank Instruments",
      user: `${admin.fullName} (${admin.company})`,
      details: { summary: `Administrator set marketplace instrument ${id} to ${available ? "available" : "hidden"}.`, referenceId: id },
    })
    const { rows } = await query(`SELECT * FROM marketplace_instruments ORDER BY created_at DESC`)
    return { ok: true, instruments: rows.map(rowToInstrument) }
  } catch (err) {
    return { ok: false, error: (err as Error).message }
  }
}

// ---------------------------------------------------------------------------
// Client: hold / release a marketplace instrument on request lifecycle.
//
// Each catalogue instrument is a UNIQUE, single-holder item. When a signed-in
// client submits a reserve/lease/purchase request it is HELD (available=false)
// so no one else can claim the same instrument; if the Administrator declines
// (or the client cancels) it is RELEASED back to the marketplace. Session-gated
// (any approved signed-in user) — NOT passcode-gated, since the client drives it.
// ---------------------------------------------------------------------------
export async function setInstrumentAvailabilityBySession(
  id: string,
  available: boolean,
): Promise<{ ok: boolean; error?: string }> {
  try {
    const user = await getSessionUser()
    if (!user) return { ok: false, error: "Not signed in." }
    await ensureTable()
    await query(`UPDATE marketplace_instruments SET available = $2, updated_at = now() WHERE id = $1`, [
      id,
      available,
    ])
    return { ok: true }
  } catch (err) {
    return { ok: false, error: (err as Error).message }
  }
}

/**
 * Release a held marketplace instrument back to the catalogue by ISIN. Used when
 * a client's reserve/lease/purchase request is declined or cancelled, so the
 * unique instrument becomes available to others again. Session-gated.
 */
export async function releaseInstrumentByIsin(isin: string): Promise<{ ok: boolean; error?: string }> {
  try {
    const user = await getSessionUser()
    if (!user) return { ok: false, error: "Not signed in." }
    const clean = (isin || "").trim()
    if (!clean) return { ok: false, error: "Missing ISIN." }
    await ensureTable()
    await query(
      `UPDATE marketplace_instruments SET available = true, updated_at = now() WHERE upper(isin) = upper($1)`,
      [clean],
    )
    return { ok: true }
  } catch (err) {
    return { ok: false, error: (err as Error).message }
  }
}

// ---------------------------------------------------------------------------
// Admin: permanently remove an instrument.
// ---------------------------------------------------------------------------
export async function removeInstrument(passcode: string, id: string): Promise<MarketplaceResult> {
  try {
    const admin = await requireAdmin(passcode)
    await ensureTable()
    const { rows: existing } = await query(`SELECT isin FROM marketplace_instruments WHERE id = $1`, [id])
    await query(`DELETE FROM marketplace_instruments WHERE id = $1`, [id])
    await logActivity({
      action: `Administrator removed a marketplace instrument`,
      category: "Bank Instruments",
      user: `${admin.fullName} (${admin.company})`,
      details: {
        summary: `Administrator removed marketplace instrument ${id}${existing[0] ? ` (ISIN ${existing[0].isin})` : ""}.`,
        referenceId: id,
      },
    })
    const { rows } = await query(`SELECT * FROM marketplace_instruments ORDER BY created_at DESC`)
    return { ok: true, instruments: rows.map(rowToInstrument) }
  } catch (err) {
    return { ok: false, error: (err as Error).message }
  }
}

// ---------------------------------------------------------------------------
// Admin: edit an existing instrument's commercial / descriptive fields.
//
// The ISIN and verification provenance are immutable (see UpdateInstrumentInput).
// Everything else — issuing bank, type, face value, terms, printout details —
// can be corrected in place without re-verifying.
// ---------------------------------------------------------------------------
export async function updateInstrument(
  passcode: string,
  input: UpdateInstrumentInput,
): Promise<PublishResult> {
  try {
    const admin = await requireAdmin(passcode)
    await ensureTable()

    const id = (input.id || "").trim()
    if (!id) return { ok: false, error: "Missing instrument id." }

    const { rows: existingRows } = await query(
      `SELECT * FROM marketplace_instruments WHERE id = $1`,
      [id],
    )
    const existing = existingRows[0]
    if (!existing) return { ok: false, error: "That instrument no longer exists." }

    if (!input.bankName?.trim()) return { ok: false, error: "The issuing bank is required." }
    if (!Number.isFinite(input.faceValue) || input.faceValue <= 0)
      return { ok: false, error: "Enter a valid face value." }

    const cusip = (input.cusip ?? "").trim().toUpperCase() || null
    if (cusip && !isValidCusip(cusip)) return { ok: false, error: "The CUSIP is not valid." }

    const commonCode = (input.commonCode ?? "").trim() || null
    const source = existing.verified_source as VerifiedSource
    // Euroclear / Clearstream instruments must keep a real 9-digit Common Code.
    if ((source === "euroclear" || source === "clearstream") && !(commonCode && /^\d{9}$/.test(commonCode))) {
      return { ok: false, error: "Euroclear/Clearstream instruments require a 9-digit Common Code." }
    }

    // Prevent an edit from colliding with a DIFFERENT instrument's identifiers.
    const dup = await findDuplicateInstrument({
      isin: existing.isin as string,
      cusip,
      commonCode,
      excludeId: id,
    })
    if (dup && dup.field !== "isin") {
      const label = dup.field === "cusip" ? `CUSIP ${cusip}` : `Common Code ${commonCode}`
      return {
        ok: false,
        error: `That ${label} already belongs to ${dup.typeFull || "another instrument"} from ${dup.bankName || "another issuer"} (${dup.id}).`,
      }
    }

    await query(
      `UPDATE marketplace_instruments SET
         cusip = $2, common_code = $3, bank_name = $4, bank_bic = $5, bank_country = $6,
         type = $7, type_full = $8, face_value = $9, currency = $10, tenor_months = $11,
         rating = $12, assignable = $13, monetizable = $14,
         issue_date = $15, maturity_date = $16, issuer_details = $17, beneficiary_terms = $18,
         delivery_method = $19, governing_law = $20, notes = $21, printout_url = $22,
         updated_at = now()
       WHERE id = $1`,
      [
        id,
        cusip,
        commonCode,
        input.bankName.trim(),
        (input.bankBic ?? "").trim(),
        (input.bankCountry ?? "").trim(),
        input.type.trim(),
        input.typeFull.trim(),
        Math.round(input.faceValue),
        (input.currency ?? "USD").trim().toUpperCase(),
        Math.max(1, Math.round(input.tenorMonths || 12)),
        (input.rating ?? "").trim(),
        input.assignable ?? true,
        input.monetizable ?? true,
        input.issueDate || null,
        input.maturityDate || null,
        (input.issuerDetails ?? "").trim() || null,
        (input.beneficiaryTerms ?? "").trim() || null,
        (input.deliveryMethod ?? "").trim() || null,
        (input.governingLaw ?? "").trim() || null,
        (input.notes ?? "").trim() || null,
        (input.printoutUrl ?? "").trim() || null,
      ],
    )

    await logActivity({
      action: `Administrator edited a marketplace instrument`,
      category: "Bank Instruments",
      user: `${admin.fullName} (${admin.company})`,
      details: {
        summary: `Administrator updated ${input.type} ${existing.isin} from ${input.bankName} (face value ${input.currency} ${Math.round(input.faceValue).toLocaleString("en-US")}).`,
        referenceId: id,
        isin: existing.isin as string,
        issuingBank: input.bankName,
      },
    })

    const { rows } = await query(`SELECT * FROM marketplace_instruments ORDER BY created_at DESC`)
    const all = rows.map(rowToInstrument)
    const updated = all.find((i) => i.id === id)!
    return { ok: true, instrument: updated, instruments: all }
  } catch (err) {
    console.log("[v0] updateInstrument failed:", (err as Error).message)
    return { ok: false, error: "The instrument could not be updated. Please try again." }
  }
}
