// ---------------------------------------------------------------------------
// Bank-instrument marketplace helpers (server-safe)
//
// PURE presentation/pricing helpers only. This module NO LONGER generates any
// instruments or identifiers. The old deterministic catalogue fabricated ISINs
// and Common Codes so they "looked authentic" — that has been removed entirely.
//
// The marketplace is now populated EXCLUSIVELY from administrator-published,
// registry-verified instruments in the `marketplace_instruments` table (see
// `app/actions/marketplace-instruments.ts`). Identifiers are never generated by
// code; they are the real values an administrator enters and that are verified
// against Bloomberg / Euroclear / Clearstream.
//
// No "use client" directive and no React imports, so it can be consumed from
// client components AND server routes.
// ---------------------------------------------------------------------------

// --- Indicative acquisition pricing ----------------------------------------
// These mirror the headline rates shown on the Instruments page pricing strip.
export const ACQUISITION_FEE_RATES = {
  /** Assignee fee — assignment of an existing instrument to the client. */
  assign: 0.002, // 0.2%
  /** Lease (collateral transfer for a term) fee on face value. */
  lease: 0.04, // 4%
  /** Outright purchase fee on face value. */
  purchase: 0.23, // 23%
} as const

export type AcquisitionAction = keyof typeof ACQUISITION_FEE_RATES

export const ACQUISITION_ACTION_LABELS: Record<AcquisitionAction, string> = {
  assign: "Assign",
  lease: "Lease",
  purchase: "Purchase",
}

export const ACQUISITION_ACTION_DESCRIPTIONS: Record<AcquisitionAction, string> = {
  assign: "Assignment of the instrument to your name (beneficiary change).",
  lease: "Collateral transfer for the instrument's term (returned at maturity).",
  purchase: "Outright purchase — full ownership of the instrument.",
}

/** Compute the indicative fee for an acquisition action on a face value. */
export function computeAcquisitionFee(action: AcquisitionAction, faceValue: number): number {
  return Math.round(faceValue * ACQUISITION_FEE_RATES[action] * 100) / 100
}

// --- Instrument type catalogue ---------------------------------------------

export interface MarketInstrumentType {
  code: string
  full: string
  /** Short rationale shown in the catalogue. */
  purpose: string
  assignable: boolean
  monetizable: boolean
}

export const MARKET_INSTRUMENT_TYPES: MarketInstrumentType[] = [
  {
    code: "SBLC",
    full: "Standby Letter of Credit",
    purpose: "Credit enhancement & payment guarantee",
    assignable: true,
    monetizable: true,
  },
  {
    code: "BG",
    full: "Bank Guarantee",
    purpose: "Performance & financial guarantee",
    assignable: true,
    monetizable: true,
  },
  {
    code: "MTN",
    full: "Medium Term Note",
    purpose: "Tradable debt security / collateral",
    assignable: true,
    monetizable: true,
  },
  {
    code: "DLC",
    full: "Documentary Letter of Credit",
    purpose: "Trade settlement instrument",
    assignable: false,
    monetizable: true,
  },
]

/** Human label for a tenor in months (instruments are "1 year and 1 day" style). */
export function tenorLabel(months: number): string {
  if (months === 12) return "12 months"
  if (months === 13) return "1 year + 1 day"
  return `${months} months`
}
