"use client"

// ---------------------------------------------------------------------------
// Admin · Document Traceability
//
// Investigate where a leaked/forwarded MCC document originated. Three ways in:
//   1. Paste the embedded token (MCCX1:…) or a bare document id (MCC-DOC-…).
//   2. Paste raw extracted text from a suspect PDF — the token is recovered from
//      anywhere inside it.
//   3. Browse recent generations and filter by account id.
//
// The authoritative answer is the server audit row (who, which account, the
// server-captured IP, the timestamp, the biometric fingerprint on file, and the
// document type). The in-file token is only the pointer back to that row.
// ---------------------------------------------------------------------------

import { useCallback, useEffect, useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import {
  Fingerprint,
  Search,
  ShieldAlert,
  User,
  Globe,
  Clock,
  FileText,
  Loader2,
  Info,
  RefreshCw,
} from "lucide-react"
import { ADMIN_PASSCODE } from "@/lib/admin-config"
import { adminExtractTrace, adminListTraces, type TraceLookupResult } from "@/app/actions/pdf-trace"
import type { DocumentTrace } from "@/lib/pdf-trace-db"

function fmtWhen(iso: string): string {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return iso
  return d.toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  })
}

function Field({ icon: Icon, label, value, mono }: { icon: typeof User; label: string; value: string; mono?: boolean }) {
  return (
    <div className="flex items-start gap-3">
      <div className="mt-0.5 rounded-md bg-secondary p-1.5">
        <Icon className="h-4 w-4 text-primary" />
      </div>
      <div className="min-w-0">
        <p className="text-xs text-muted-foreground">{label}</p>
        <p className={`text-sm text-foreground break-words ${mono ? "font-mono" : "font-medium"}`}>{value}</p>
      </div>
    </div>
  )
}

function TraceResultCard({ result }: { result: TraceLookupResult }) {
  const trace = result.trace
  const payload = result.payload

  return (
    <Card className="border-primary/30 bg-primary/5">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-base font-semibold text-foreground">
          <ShieldAlert className="h-5 w-5 text-primary" />
          {trace ? "Document traced" : "Token decoded — no server record"}
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {trace ? (
          <div className="grid gap-4 sm:grid-cols-2">
            <Field icon={FileText} label="Document ID" value={trace.docId} mono />
            <Field icon={FileText} label="Type" value={trace.kind} />
            <Field icon={User} label="Generated by (account)" value={trace.account} />
            <Field icon={User} label="Account ID" value={trace.userId} mono />
            <Field icon={Globe} label="Origin IP (server-captured)" value={trace.ipAddress || "Unknown"} mono />
            <Field icon={Clock} label="Generated at" value={fmtWhen(trace.createdAt)} />
            <Field
              icon={Fingerprint}
              label="Biometric fingerprint on file"
              value={trace.biometricHash ? `${trace.biometricHash.slice(0, 24)}…` : "None enrolled"}
              mono
            />
            <Field icon={FileText} label="Filename" value={trace.filename || "—"} />
            {trace.title ? <Field icon={FileText} label="Title" value={trace.title} /> : null}
            {trace.userAgent ? <Field icon={Info} label="Device / browser" value={trace.userAgent} /> : null}
            {trace.isDemo ? (
              <div className="sm:col-span-2">
                <Badge variant="secondary">Demo account · exports were blocked</Badge>
              </div>
            ) : null}
          </div>
        ) : payload ? (
          <div className="space-y-4">
            <p className="text-sm text-muted-foreground text-pretty">
              The embedded token is valid, but no matching audit row exists on the server (it may have been
              purged, or predates traceability). The details below come from inside the document itself and
              are therefore less authoritative than a server record.
            </p>
            <div className="grid gap-4 sm:grid-cols-2">
              <Field icon={FileText} label="Document ID" value={payload.docId} mono />
              <Field icon={FileText} label="Type" value={payload.kind} />
              <Field icon={User} label="Account (embedded)" value={payload.account} />
              <Field icon={User} label="Account ID (embedded)" value={payload.uid} mono />
              <Field icon={Clock} label="Generated at (embedded)" value={fmtWhen(new Date(payload.ts).toISOString())} />
            </div>
          </div>
        ) : null}
      </CardContent>
    </Card>
  )
}

export function DocumentTraceability() {
  const [needle, setNeedle] = useState("")
  const [looking, setLooking] = useState(false)
  const [lookupError, setLookupError] = useState<string | null>(null)
  const [result, setResult] = useState<TraceLookupResult | null>(null)

  const [filterUser, setFilterUser] = useState("")
  const [recent, setRecent] = useState<DocumentTrace[]>([])
  const [loadingRecent, setLoadingRecent] = useState(false)

  const loadRecent = useCallback(async () => {
    setLoadingRecent(true)
    try {
      const res = await adminListTraces(ADMIN_PASSCODE, filterUser.trim() || undefined)
      if (res.ok) setRecent(res.traces)
    } finally {
      setLoadingRecent(false)
    }
  }, [filterUser])

  useEffect(() => {
    void loadRecent()
    // Intentionally run once on mount; the filter has its own button.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const runLookup = useCallback(async () => {
    const value = needle.trim()
    if (!value) {
      setLookupError("Enter a document id, token, or paste the document text.")
      return
    }
    setLooking(true)
    setLookupError(null)
    setResult(null)
    try {
      const res = await adminExtractTrace(ADMIN_PASSCODE, value)
      if (!res.ok) {
        setLookupError(res.error || "Lookup failed.")
        return
      }
      if (!res.trace && !res.payload) {
        setLookupError(res.error || "No matching document was found.")
        return
      }
      setResult(res)
    } catch {
      setLookupError("The lookup failed. Please try again.")
    } finally {
      setLooking(false)
    }
  }, [needle])

  return (
    <div className="space-y-6">
      <Card className="border-border bg-card">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-lg font-semibold text-foreground">
            <Fingerprint className="h-5 w-5 text-primary" />
            Document Traceability
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm text-muted-foreground text-pretty">
            Every document generated on the platform carries a hidden trace token and is recorded in a
            tamper-proof server log. Paste a token (<span className="font-mono">MCCX1:…</span>), a document
            id (<span className="font-mono">MCC-DOC-…</span>), or the extracted text of a suspect PDF to
            identify who generated it, for which account, and from where.
          </p>

          <div className="space-y-2">
            <label htmlFor="trace-needle" className="text-sm font-medium text-foreground">
              Token, document id, or pasted document text
            </label>
            <Textarea
              id="trace-needle"
              value={needle}
              onChange={(e) => setNeedle(e.target.value)}
              placeholder="MCCX1:…  or  MCC-DOC-…  or paste the extracted PDF text here"
              rows={3}
              className="font-mono text-sm"
            />
          </div>

          {lookupError ? (
            <p className="text-sm text-destructive">{lookupError}</p>
          ) : null}

          <Button onClick={runLookup} disabled={looking}>
            {looking ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Search className="mr-2 h-4 w-4" />}
            Trace document
          </Button>

          <div className="flex items-start gap-2 rounded-lg border border-border bg-secondary/40 p-3">
            <Info className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" />
            <p className="text-xs text-muted-foreground text-pretty">
              Documents are produced in the browser, so a determined user can strip the in-file token. When
              that happens the token lookup will fail — use the recent-activity log below (searchable by
              account id and time) as the authoritative fallback, since those rows live on the server and
              cannot be altered by the account holder.
            </p>
          </div>
        </CardContent>
      </Card>

      {result ? <TraceResultCard result={result} /> : null}

      <Card className="border-border bg-card">
        <CardHeader>
          <CardTitle className="flex items-center justify-between gap-2 text-base font-semibold text-foreground">
            <span className="flex items-center gap-2">
              <Clock className="h-5 w-5 text-primary" />
              Recent document generations
            </span>
            <Button variant="outline" size="sm" onClick={loadRecent} disabled={loadingRecent}>
              {loadingRecent ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              ) : (
                <RefreshCw className="mr-2 h-4 w-4" />
              )}
              Refresh
            </Button>
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex flex-col gap-2 sm:flex-row">
            <Input
              value={filterUser}
              onChange={(e) => setFilterUser(e.target.value)}
              placeholder="Filter by account id (optional)"
              className="font-mono text-sm"
            />
            <Button variant="secondary" onClick={loadRecent} disabled={loadingRecent}>
              <Search className="mr-2 h-4 w-4" />
              Apply filter
            </Button>
          </div>

          {recent.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              {loadingRecent ? "Loading…" : "No document generations recorded yet."}
            </p>
          ) : (
            <div className="divide-y divide-border overflow-hidden rounded-lg border border-border">
              {recent.map((t) => (
                <button
                  key={t.docId}
                  type="button"
                  onClick={() => {
                    setNeedle(t.docId)
                    setResult({ ok: true, trace: t })
                    if (typeof window !== "undefined") window.scrollTo({ top: 0, behavior: "smooth" })
                  }}
                  className="flex w-full flex-col gap-1 p-3 text-left transition-colors hover:bg-secondary sm:flex-row sm:items-center sm:justify-between"
                >
                  <div className="min-w-0">
                    <p className="truncate text-sm font-medium text-foreground">
                      {t.account}
                      {t.isDemo ? <span className="ml-2 text-xs text-muted-foreground">(demo)</span> : null}
                    </p>
                    <p className="truncate font-mono text-xs text-muted-foreground">{t.docId}</p>
                  </div>
                  <div className="flex shrink-0 items-center gap-2">
                    <Badge variant="secondary" className="capitalize">
                      {t.kind}
                    </Badge>
                    <span className="text-xs text-muted-foreground">{fmtWhen(t.createdAt)}</span>
                  </div>
                </button>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
